apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: databricks-frontend-logs
  namespace: databricks
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: default
  
