apiVersion: v1
kind: Service
metadata:
  name: databricks-service-frontend
  namespace: databricks
spec:
  type: LoadBalencer
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 30036
