apiVersion: v1
kind: Service
metadata:
  name: databricks-service-frontend
  namespace: databricks
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
